version: "3.3"

services:
  web:
    container_name: reignapp
    restart: always
    build: .
    ports: 
      - "8080:8080"
    links: 
      - mongo
    volumes: 
      - .:/usr/src/app

  mongo:
    container_name: reign_db
    image: mongo
    ports: 
     - "27018:27017"
